# Putting data to good use {#gooduse}

## Failure mode

We hope to have convinced readers that the data presented in @WalkdenEa2023 does provide strong evidence in favour of the claims put forward by the authors.
However, the authors clearly think they do.
How did this happen?
As we showed in Section \@ref(findingout), the authors are looking for support of the Trudgill's theory of language change.
This theory, we argued, consists of a huge and mostly implicit conjunction of substantive and auxiliary hypotheses.
From these hypotheses, the authors derived (verbally, not using any strict logic) particular hypotheses about language changes in England and the Hispanopohone world.
These particular hypotheses along with many additional implicit auxiliary hypotheses were added to the conjunct of hypotheses already assumed.
From the particular hypotheses the authors implicitly derived statistical hypotheses (about the occurrence probabilities of overtly inflected pre-nominal elements in certain regions and times in England as well as the occurrence probability of subject drop in Spanish-speaking countries and regions).
These statistical hypotheses were converted to Null hypotheses of the form "*Variable V does not have an influence on the respective probability.*", which were tested as parts of complex statistical models.
From a rejection of these hypotheses using discredited NHST logic, positive inferences were made all the way back through the network of hypotheses to the effect of "*Trudgill's theory is correct.*" and "*The method proposed by us is effective in corroborating Trudgill's theory.*"

It should be obvious that this is a risky approach.
Not only are two major positive inferences attempted, but the whole problem of underdetermination is completely ignored.
Also, the amount of evidence (measured in the number of linguistic examples used in the statistical is minute compared to the complexity of the network of hypotheses.
Unfortunately, the mechanical application of NHST and some incorrect analyses of the data (in th form of unweighted aggregations) invalidate the rejection of the weak Null hypotheses, and hence there is no inference to be made at all, neither a modest one nor an exceptional one.
We can only speculate why the errors were not detected by the authors, the main author, the editors, and the reviewers.
Instead of ending on such an uncomfortable note, we'd like to suggest three remedies to avoid such results to be published in the future.
None of these is original in the sense that we did not come up with them.
Other areas have similar problems, and many researchers have had very good ideas to remedy these problems.

## Remedy 1: disciplined inference and better theories

We need to be modest about our inferences and acknowledge the network of hypotheses and the intrinsic underdeterminism in linguistics.
Testing theories is a piecemeal exercise, and we should be aware that any corpus study or experiment that we report should focus on the most specific subset of hypotheses from the network.
It would be a major advantage if our theories made more precise predictions.
Ideally, theories should at least predict a numerical range for the expected measurements in a study.
This would certainly sharpen our particular and statistical hypotheses to be tested.
Alternatively, numerical predictions can also be obtained from experimental traditions, which only works if the exact same thing is measured over and over again.
This allows us to conduct meta-analyses and establish numerical expectations [see @Vasishth2015 for an example from psycholinguistics].

If possible at all, numerical expectations should be used to test statistical hypotheses using Neyman-Pearson logic [@NeymanPearson1933;@Neyman1937;@Neyman1957] or extensions thereof such as severity [@MayoSpanos2004].
These allow us to make valid positive inferences beyond mere rejection of uninformative Null hypotheses, but they usually require predictions about the numerical range we expect the results to land in.

Finally, researchers need better training in data analysis and statistical inference.
We have seen many situations where postgraduates in linguistics were simply sent off to a one-week summer school and expected to return fully competent in the application of statistical methods.
Many are also self-taught and rely on case-by-case internet searches to solve their problems.
Often, dissertation supervisors appear to be not an ounce more competent than their candidates in the application of statistical methods.
To the extent that this is not just an inadmissible impression from our episodic memory, it is indeed problematic.

## Remedy 2: open data as part of the review process

Editors and reviewers must receive as much relevant information as possible in order to spot problems with statistical models.
Also, a look at the data should be a required part of the review process, and reviewers should be competent to spot errors with ease.
While there are clues in @WalkdenEa2023 as published, the real problems are only revealed through a reanalysis of the data.
In our own experience, reviewers (even for corpus linguistics journals and journals with an empirical focus) rarely spot errors in the design of studies or the statistical analysis of the data.
This might be because they have no access to the data, do not examine the data, or lack the skills to examine the data.
Rather, they tend do demand more in-depth theoretical discussion, which more often than not does not make the paper's contribution to scientific progress any more sound or relevant.

A related issue is the lack of best-practice standards for linguistics journals.
As it stands, most journals will accept any submission that reports a GLM or any other type of statistics, and it is the authors' choice which type of quality assurance they apply.
As authors, we find this nerve-wrecking, especially as some reviewers are not shy to demand the quality assurance that suits their personal taste, which makes preparing publications rather difficult.
A journal that has no best-practice guidelines for statistical methods should reject any papers applying those methods (unless the paper specifically makes an original methodological contribution, for example by introducing a new method altogether).

## Remedy 3: negative findings an pre-registration

Universities and funding agencies require researchers to publish as many results as possible, and postgraduate students are under immense pressure to make themselves known by publishing in a frenzy.
At the same time, it is very difficult to publish negative results.
It would be demanding to re-write @WalkdenEa2023 along the following lines and still make it sound interesting to reviewers:
"*We did not find evidence for Trudgill's theory in our data, but we'll keep looking.*"

Pre-registration is an attempt to alleviate this problem.
Researchers submit a paper describing the motivation for a study and the design of the study *without having executed the study* and thus without having spent the time and money.
The paper is accepted or rejected based on the submission, and whatever the results, the paper is published if the study was executed as designed.
This makes negative results publishable and should allow researchers to be more critical with their own data.
However, while we would welcome journals offering pre-registration, we think it does not solve too many problems.
As negative results would not receive nearly as many citations as positive results, not much might be gained.

In closing, we'd like to point out that philology used to be a field where careful close readings of texts were performed in order to gain insights about their linguistic and cultural relevance.
It was not bound by the scientific method and had no interest in data analysis and statistics.
A major reason used to be that there are just not enough textual data covering all relevant times and places in order to do reliable statistical analysis.
In many cases, we wonder whether this has really changed considerably, and why many researchers appear fixated on quantitative analyses where traditional philological analyses might be in order.
If, however, quantitative analyses are not performed with the required rigour, and if theories are not taken seriously as monstrous underdetermined networks of intertwined hypotheses, nothing will be gained in a quantitative turn.

