---
title: "Substantive and statistical hypotheses in data-oriented linguistics"
author: "Roland Schäfer, Friedrich-Schiller-Universität Jena"
date: "2024"
output:
  html_document:
    number_sections: true
  pdf_document: 
    latex_engine: xelatex
    number_sections: true
  word_document: default
bibliography: Hypotheses.bib
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = "")
set.seed(911)

require(lme4)
require(performance)
require(MuMIn)
require(vioplot)
require(LaplacesDemon)

load("Subject.RData")
load("Agreement.RData")

# For prettier printing.

AgreementData$Dialect <- factor(AgreementData$Dialect, levels = c("Southern", "EM", "WM", "Northern"))
levels(AgreementData$Dialect) <- c("South", "WestMidlands", "EastMidlands", "North")
AgreementAggregateData$Dialect <- factor(AgreementAggregateData$Dialect, levels = c("Southern", "EM", "WM", "Northern"))
levels(AgreementAggregateData$Dialect) <- c("South", "EastMidlands", "WestMidlands", "North")
AgreementData$POS <- as.factor(AgreementData$POS)

colnames(SubjectData)[3] <- "Subject"
colnames(SubjectData)[7] <- "Text"
colnames(SubjectData)[10] <- "Macroregion"

SubjectData$Subject <- ifelse(SubjectData$Subject == "NULL", 0, 1)
levels(SubjectData$Genre) <- c("Nonliterary", "Literary", "Supplemental")

# Calculate precision and recall at a certain threshold t.
PrecisionRecall <- function(predictions, data, threshold) {
  .pt <- ifelse(predictions <= threshold, 0, 1)
  .m <- table(factor(.pt, levels=c(0,1)), factor(data, levels=c(0,1)))
  .gt <- sum(.m)
  .prec <- .m["1","1"]/sum(.m["1",])
  .prec <- ifelse(is.na(.prec), 0, .prec)
  .rec <- .m["1","1"]/sum(.m[,"1"])
  .rec <- ifelse(is.na(.rec), 0, .rec)
  list(Precision = .prec, Recall = .rec)
}

# Calculate the proportion of correct predictions at threshold t.
Correct <- function(predictions, data, threshold) {
  .pt <- ifelse(predictions <= threshold, 0, 1)
  .m <- table(.pt==data)
  .m[2]/sum(.m)
}

ReportGLM <- function(model, data = NULL,
                      name = NULL,
                      intercept.descriptor = NULL,
                      lom.descriptors = NULL,
                      stars = c(0.05, 0.01, 0.001),
                      coeff.round = 2,
                      sigma.round = 2,
                      p.round = 4,
                      aic.round = 2,
                      r2.round = 4,
                      acc.round = 2) {
  
  require(lme4)
  require(performance)
  
  # Analyse model as passed.
  .sum <- summary(model)
  .r2 <- r2(model)
  .coeffs <- .sum$coefficients
  
  # Models with no fixed effects don't get a table.
  if (nrow(.coeffs)>1) {
    .coeffs <- .coeffs[,c(1,3,4)]
    colnames(.coeffs) <- c("Coefficient", "Sigma", "P")
    
    # Calculate stars with unrounded P.
    if (!is.null(stars)) {
      .stars <- rep("", nrow(.coeffs))
      for (star in stars) .stars <- ifelse(.coeffs[,"P"] < star, paste0(.stars, "*"), .stars)
    }

    .coeffs[,1] <- round(.coeffs[,1], coeff.round)
    .coeffs[,2] <- round(abs(.coeffs[,2]), sigma.round)
    .coeffs[,3] <- round(abs(.coeffs[,3]), p.round)
    .facs <- colnames(attr(terms(model), "factors"))
  
    # Change intercept label if passed.
    if (!is.null(intercept.descriptor)) rownames(.coeffs)[1] <- intercept.descriptor
  
    # Find table for term headers.
    # Create regexes with regexes. Ah-haha!
    .regex <- unlist(lapply(.facs, function(s) {
      s <- gsub(':([^:]+)', ':\\1([^:]\\+|)', s)
      s <- gsub('^([^:]+)', '\\1([^:]\\+|)', s)
      s
    }))
    
    # Same for the replacement patterns.
    .subs <- unlist(lapply(.facs, function(s) {
      s <- gsub(':([^:]+)', ':\\\\0', s)
      s <- gsub('^([^:]+)', '\\\\0', s)
      # Unfortunately, regexes cannot count. Hence, some hacking.
      .s <- unlist(strsplit(s, '\\0', fixed=T))
      s <- ""
      for (k in 1:length(.s)) s <- paste0(s, .s[k], "\\", k)
      s
    }))
  
    # Find positions where term label changes.
    .splits <- c(1, unlist(lapply(.regex, function(reg) {
      grep(reg, rownames(.coeffs))[1]
    })))
  
    # Annotate regressors with LOMs if passed and correct length.
    if ((!is.null(lom.descriptors)) & (length(lom.descriptors)==length(.facs)))
      .facs <- paste0(.facs, " (", lom.descriptors, ")")
  
    .levels <- unname(unlist(rownames(.coeffs)))
    for (h in length(.regex):1) {
      .levels <- sub(.regex[h], .subs[h], .levels)
    }
    
    # For interactions of numerical terms, remove redundant colons.
    .levels <- gsub(":+", ":", .levels)
    .levels <- gsub("^:", "", .levels)
    .levels <- gsub(":$", "", .levels)
    
    .coeffs <- cbind(
      data.frame(
        Term = rep("", nrow(.coeffs)),
        Level <- .levels
      ),
      .coeffs
    )
  
    colnames(.coeffs)[2] <- "Level"
    .facs <- c("Intercept", .facs)
    .coeffs[.splits, "Term"] <- .facs
    rownames(.coeffs) <- 1:nrow(.coeffs)
    
    # Attach stars if desired.
    if (!is.null(stars)) .coeffs <- data.frame(.coeffs, "Sig." = .stars)
  } 
  else {.coeffs <- NULL}

  # For mixed models, get random effects.
  if (is(model, "merMod")) {
    .levels <- unlist(lapply(ranef(model), function(re) nrow(re)))
    .randomr <- paste0(" It includes the following random effects: ", 
                       paste(names(.levels), " with ", unname(.levels), " levels", sep = "", collapse =", "), ".")
  } else {
    .levels <- NULL
    .randomr <- ""
  }
  
  # If we have data, get accuracy.
  if (!is.null(data)) {
    .accuracy <- Correct(predict(model, type="response"), data, 0.5)
    .baserate <- max(table(data))/sum(table(data))
    .accuracyr <- paste0(" The prediction accuracy on the training data at a probability threshold of 0.5 is ", round(.accuracy, acc.round), " given a base rate of ", round(.baserate, acc.round), ".")
  }
  else {
    .accuracy <- NULL
    .baserate <- NULL
    .accuracyr <- ""
  }
  
  # Process R2 for report.
  .r2r <- unlist(lapply(.r2, function(r) {paste0(names(r), "=", round(unname(r), r2.round))}))
  .r2r <- gsub('R2', 'R²', paste(unlist(.r2r), collapse=", "))
  
  .name <- ifelse(!is.null(name), paste0("The ", name, " "), 'This ')
  
  list(
    "Table"    = .coeffs,
    "Random"   = .levels,
    "R2"       = .r2,
    "AIC"      = round(AIC(model), aic.round),
    "Accuracy" = round(.accuracy, acc.round),
    "Baserate" = round(.baserate, acc.round),
    "Report"   = paste0(.name, "is a ", family(model)$family, " model with a ",
                        family(model)$link, " link. AIC=", round(AIC(model), aic.round),
                        ", ", .r2r, ".", .accuracyr, .randomr)
    )
}

```

<!--

```{r, child=c('child_1_findout.Rmd')}
```

-->

# Data and inferences in @WalkdenEa2023

```{r, child=c('child_2a_study1.Rmd')}
```

```{r, child=c('child_2b_study2.Rmd')}
```

```{r, child=c('child_2c_foundout.Rmd')}
```

<!--

```{r, child=c('child_3_gooduse.Rmd')}
```

-->

# References
